export const PHRASE_DICTIONARY: Record<string, string> = {
  // Common Symptoms (EN -> BN)
  "fever": "জ্বর",
  "high fever": "তীব্র জ্বর",
  "low-grade fever": "হালকা জ্বর",
  "cough": "কাশি",
  "sore throat": "গলা ব্যথা",
  "runny nose": "নাক দিয়ে জল পড়া",
  "headache": "মাথাব্যথা",
  "nausea": "বমি বমি ভাব",
  "vomiting": "বমি",
  "diarrhea": "ডায়রিয়া",
  "stomach pain": "পেট ব্যথা",
  "dizziness": "মাথা ঘোরা",
  "rash": "ফুসকুড়ি",
  "allergy": "অ্যালার্জি",
  "back pain": "পিঠ ব্যথা",
  "body ache": "শরীরে ব্যথা",
  "fatigue": "ক্লান্তি",
  "weakness": "দুর্বলতা",
  "shortness of breath": "শ্বাসকষ্ট",
  "chest pain": "বুকে ব্যথা",
  "sneezing": "হাঁচি",
  "congestion": "নাক বন্ধ",
  "red eyes": "চোখ লাল",
  "itchy eyes": "চোখ চুলকানি",
  "ear pain": "কানে ব্যথা",
  "toothache": "দাঁত ব্যথা",
  "burning urination": "প্রস্রাবে জ্বালাপোড়া",
  "frequent urination": "ঘন ঘন প্রস্রাব",
  "pregnancy cramps": "গর্ভাবস্থায় খিঁচুনি",
  "baby colic": "শিশুর পেট ব্যথা",
  "constipation": "কোষ্ঠকাঠিন্য",
  "swelling": "ফোলা",
  "bleeding": "রক্তপাত",
  "itching": "চুলকানি",
  "muscle pain": "পেশী ব্যথা",
  "joint pain": "গাঁটে ব্যথা",
  "high blood pressure": "উচ্চ রক্তচাপ",
  "asthma": "হাঁপানি",
  "infection": "সংক্রমণ",
  "morning sickness": "মর্নিং সিকনেস",
  "baby kick": "শিশুর লাথি",
  "ultrasound": "আল্ট্রাসাউন্ড",
  "delivery": "প্রসব",
  "labor": "প্রসব বেদনা",
  "contraction": "সংকোচন",
  "breastfeeding": "স্তন্যপান",
  "cold": "ঠান্ডা",
  "flu": "ইনফ্লুয়েঞ্জা",
  "wound": "ক্ষত",
  "burn": "পোড়া",
  "heart attack": "হার্ট অ্যাটাক",
  "stroke": "স্ট্রোক",
  "diabetes": "ডায়াবেটিস",
  "anemia": "রক্তশূন্যতা",
  "dehydration": "পানিশূন্যতা",
  "insomnia": "অনিদ্রা",
  "anxiety": "উদ্বেগ",
  "depression": "বিষণ্নতা",
  "loss of appetite": "ক্ষুধা হ্রাস",
  "blurred vision": "ঝাপসা দৃষ্টি",
  "numbness": "অসাড়তা",
  "chill": "কাঁপুনি",
  "sweating": "ঘাম",
  "pale skin": "ফ্যাকাশে ত্বক",
  "mouth ulcer": "মুখের ঘা",
  "indigestion": "বদহজম",
  "heartburn": "বুক জ্বালাপোড়া",
  "pregnancy": "গর্ভাবস্থা",
  "medicine": "ঔষধ",
  "hospital": "হাসপাতাল",
  "doctor": "ডাক্তার",
  "nurse": "নার্স",
  "appointment": "অ্যাপয়েন্টমেন্ট",
  "emergency": "জরুরি",
  "ambulance": "অ্যাম্বুলেন্স",
  "clinic": "ক্লিনিক",
  "painkiller": "ব্যথানাশক",
  "vitamins": "ভিটামিন",
  "symptoms": "উপসর্গ",

  // Phrases
  "i have a fever": "আমার জ্বর হয়েছে",
  "my head hurts": "আমার মাথা ব্যথা করছে",
  "is it safe?": "এটা কি নিরাপদ?",
  "call an ambulance": "অ্যাম্বুলেন্স ডাকুন",
  "hospital near me": "আমার কাছের হাসপাতাল",
  "i need help": "আমার সাহায্য দরকার",

  // Inverse Mapping (BN -> EN)
  "জ্বর": "fever",
  "তীব্র জ্বর": "high fever",
  "হালকা জ্বর": "low-grade fever",
  "কাশি": "cough",
  "গলা ব্যথা": "sore throat",
  "নাক দিয়ে জল পড়া": "runny nose",
  "মাথাব্যথা": "headache",
  "বমি বমি ভাব": "nausea",
  "বমি": "vomiting",
  "ডায়রিয়া": "diarrhea",
  "পেট ব্যথা": "stomach pain",
  "মাথা ঘোরা": "dizziness",
  "ফুসকুড়ি": "rash",
  "অ্যালার্জি": "allergy",
  "পিঠ ব্যথা": "back pain",
  "শরীরে ব্যথা": "body ache",
  "ক্লান্তি": "fatigue",
  "দুর্বলতা": "weakness",
  "শ্বাসকষ্ট": "shortness of breath",
  "বুকে ব্যথা": "chest pain",
  "হাঁচি": "sneezing",
  "নাক বন্ধ": "congestion",
  "চোখ লাল": "red eyes",
  "চোখ চুলকানি": "itchy eyes",
  "কানে ব্যথা": "ear pain",
  "দাঁত ব্যথা": "toothache",
  "প্রস্রাবে জ্বালাপোড়া": "burning urination",
  "ঘন ঘন প্রস্রাব": "frequent urination",
  "গর্ভাবস্থায় খিঁচুনি": "pregnancy cramps",
  "শিশুর পেট ব্যথা": "baby colic",
  "কোষ্ঠকাঠিন্য": "constipation",
  "ফোলা": "swelling",
  "রক্তপাত": "bleeding",
  "চুলকানি": "itching",
  "পেশী ব্যথা": "muscle pain",
  "গাঁটে ব্যথা": "joint pain",
  "উচ্চ রক্তচাপ": "high blood pressure",
  "হাঁপানি": "asthma",
  "সংক্রমণ": "infection",
  "মর্নিং সিকনেস": "morning sickness",
  "শিশুর লাথি": "baby kick",
  "আল্ট্রাসাউন্ড": "ultrasound",
  "প্রসব": "delivery",
  "প্রসব বেদনা": "labor",
  "সংকোচন": "contraction",
  "স্তন্যপান": "breastfeeding",
  "ঠান্ডা": "cold",
  "ইনফ্লুয়েঞ্জা": "flu",
  "ক্ষত": "wound",
  "পোড়া": "burn",
  "হার্ট অ্যাটাক": "heart attack",
  "স্ট্রোক": "stroke",
  "ডায়াবেটিস": "diabetes",
  "রক্তশূন্যতা": "anemia",
  "পানিশূন্যতা": "dehydration",
  "অনিদ্রা": "insomnia",
  "উদ্বেগ": "anxiety",
  "বিষণ্নতা": "depression",
  "ক্ষুধা হ্রাস": "loss of appetite",
  "ঝাপসা দৃষ্টি": "blurred vision",
  "অসাড়তা": "numbness",
  "কাঁপুনি": "chill",
  "ঘাম": "sweating",
  "ফ্যাকাশে ত্বক": "pale skin",
  "মুখের ঘা": "mouth ulcer",
  "বদহজম": "indigestion",
  "বুক জ্বালাপোড়া": "heartburn",
  "গর্ভাবস্থা": "pregnancy",
  "ঔষধ": "medicine",
  "হাসপাতাল": "hospital",
  "ডাক্তার": "doctor",
  "নার্স": "nurse",
  "অ্যাপয়েন্টমেন্ট": "appointment",
  "জরুরি": "emergency",
  "অ্যাম্বুলেন্স": "ambulance",
  "ক্লিনিক": "clinic",
  "ব্যথানাশক": "painkiller",
  "ভিটামিন": "vitamins",
  "উপসর্গ": "symptoms",
};

export const translateOffline = (text: string, direction: 'en-bn' | 'bn-en'): string | null => {
  const input = text.toLowerCase().trim();
  
  // 1. Exact Phrase Match
  if (PHRASE_DICTIONARY[input]) return PHRASE_DICTIONARY[input];
  
  // 2. Multi-word match (only if all words are known to prevent mixed results)
  const words = input.split(' ');
  if (words.length > 1) {
    const translatedWords = words.map(word => PHRASE_DICTIONARY[word] || null);
    if (translatedWords.every(w => w !== null)) {
      return translatedWords.join(' ');
    }
  }
  
  return null;
};
